name: Mod Build

on:
  workflow_dispatch:
  push:
    branches:
      - releases/**
    paths:
      - src/**
      - versions/**
      - build.gradle
      - gradle.properties
      - settings.gradle

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    env:
      CI_BUILD: true
      PR_BUILD: false
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v3.6.0
        with:
          distribution: zulu
          java-version: 21

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew build

      - run: ./gradlew build publishMods
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
